trigger:
- master

pool:
  name: PIpelines-test

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '33e7a7ff-c8e5-42ce-8ff3-7b97cfc65690'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ArmPipelines-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Samurai-aj/ArmPipelines/master/azuredeploy.json'
    overrideParameters: '-projectName myarmpipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
    
    
    
